const products=[{id:1,name:'Rose Seamless Short Leggings',price:24.99,old:34.99,cat:'Fitness',image:'assets/products/leggings.jpg',tag:'BESTSELLER'},{id:2,name:'LED Facial Mask',price:39.99,old:59.99,cat:'Beauty',image:'assets/products/led-mask.jpg',tag:'TRENDING'},{id:3,name:'Minimalist Crossbody Bag',price:29.99,old:44.99,cat:'Fashion',image:'assets/products/bag.jpg',tag:'NEW'},{id:4,name:'Portable Mini Projector',price:49.99,old:69.99,cat:'Tech',image:'assets/products/projector.jpg',tag:'HOT'},{id:5,name:'Smart Water Bottle',price:27.99,old:39.99,cat:'Lifestyle',image:'assets/products/bottle.jpg'},{id:6,name:'Sculpting Face Roller',price:14.99,old:22.99,cat:'Beauty',image:'assets/products/roller.jpg'},{id:7,name:'Wireless Desk Lamp',price:32.99,old:46.99,cat:'Home',image:'assets/products/lamp.jpg'},{id:8,name:'Travel Organizer Set',price:19.99,old:29.99,cat:'Travel',image:'assets/products/organizer.jpg'}];
let cart=JSON.parse(localStorage.getItem('z3r0-cart')||'[]');
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'EUR'}).format(n);
function save(){localStorage.setItem('z3r0-cart',JSON.stringify(cart));renderCart();updateBadge()}
function updateBadge(){document.querySelectorAll('[data-cart-count]').forEach(x=>x.textContent=cart.reduce((s,i)=>s+i.qty,0))}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p)return;const item=cart.find(x=>x.id===id);item?item.qty++:cart.push({id,qty:1});save();openCart()}
function removeFromCart(id){cart=cart.filter(x=>x.id!==id);save()}
function changeQty(id,d){const item=cart.find(x=>x.id===id);if(!item)return;item.qty+=d;if(item.qty<1)removeFromCart(id);else save()}
function renderProducts(filter='All'){const root=document.querySelector('#product-grid');if(!root)return;const list=filter==='All'?products:products.filter(p=>p.cat===filter);root.innerHTML=list.map(p=>`<article class="product-card"><div class="product-image"><span class="tag">${p.tag||p.cat}</span><img src="${p.image}" alt="${p.name}" onerror="this.style.display='none'"></div><div class="product-info"><p class="product-title">${p.name}</p><div><span class="price">${money(p.price)}</span><span class="old-price">${money(p.old)}</span></div><button class="add" onclick="addToCart(${p.id})">Añadir al carrito</button></div></article>`).join('')}
function renderCart(){const root=document.querySelector('#cart-items'),total=document.querySelector('#cart-total');if(!root)return;if(!cart.length){root.innerHTML='<div class="empty">Tu carrito está vacío.</div>';total.textContent=money(0);return}root.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id);return `<div class="cart-item"><img src="${p.image}" alt=""><div><strong>${p.name}</strong><div>${money(p.price)} × ${i.qty}</div><button class="icon-btn" onclick="changeQty(${p.id},-1)">−</button> <button class="icon-btn" onclick="changeQty(${p.id},1)">+</button></div><button class="icon-btn" onclick="removeFromCart(${p.id})">×</button></div>`}).join('');total.textContent=money(cart.reduce((s,i)=>s+(products.find(p=>p.id===i.id).price*i.qty),0))}
function openCart(){document.querySelector('#cart-drawer')?.classList.add('open');document.querySelector('#overlay')?.classList.add('open');renderCart()}
function closeCart(){document.querySelector('#cart-drawer')?.classList.remove('open');document.querySelector('#overlay')?.classList.remove('open')}
function checkout(){if(!cart.length){alert('Tu carrito está vacío.');return}alert('Demo de checkout: conecta aquí Stripe, PayPal o tu proveedor de pagos.');}
function filterProducts(cat){document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===cat));renderProducts(cat)}
document.addEventListener('DOMContentLoaded',()=>{renderProducts();renderCart();updateBadge();document.querySelector('#year').textContent=new Date().getFullYear();document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>filterProducts(b.dataset.filter)));document.querySelector('#newsletter')?.addEventListener('submit',e=>{e.preventDefault();alert('Gracias por suscribirte.');e.target.reset()})});